# Generated by Django 2.1.7 on 2019-04-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0005_auto_20190416_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score_contacts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='score_tasks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
