# Generated by Django 2.1.7 on 2019-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0006_auto_20190416_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment_calendar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_contacts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_tasks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
