# Generated by Django 2.1.7 on 2019-04-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0007_auto_20190416_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comment_hub',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='score',
            new_name='score_hub',
        ),
    ]
