# Generated by Django 2.1.7 on 2019-04-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0008_auto_20190417_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score_hub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
